/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types generated with workerd@1.20260426.1 2024-04-01 nodejs_compat
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		DB: D1Database;
		JWT_PUBLIC_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
